SRC =   
LIBS=

SRC += MMITSS_MRP_TrafficControllerInterface.cpp Signal.cpp Array.cpp Config.cpp

TGT:=MMITSS_MRP_TrafficControllerInterface
MMITSS=../../../sdk/mmitss
CFLAGS:=-DPRINT_LOG -g
INCLUDES:=-I. -I$(MMITSS)/include/libj2735
LIBS+=-L$(MMITSS)/lib 

all:TOOLCHAIN=../../../sdk/rse/toolchain
all:CC=$(TOOLCHAIN)/bin/i386-linux-uclibc-g++
all:LD=$(TOOLCHAIN)/bin/i386-linux-uclibc-ld
all:INCLUDES+=-I$(TOOLCHAIN)/include -I$(TOOLCHAIN)/usr/include
all:LIBS+=-L$(TOOLCHAIN)/lib -L$(TOOLCHAIN)/usr/lib -luClibc++ -lj2735-rse

linux:TOOLCHAIN=
linux:CC=g++
linux:LD=ld
linux:LIBS+=-lj2735-linux

LIBS+=-lnetsnmp -lstdc++ -lm
OBJ = $(patsubst %.cpp, %.o, ${SRC})

all:	$(TGT)
linux:	$(TGT)

$(TGT): $(OBJ)
	${CC} ${CFLAGS} ${INCLUDES} $(OBJ) -o $(TGT) $(LIBS)

%.o: %.cpp
	${CC} ${CFLAGS} ${INCLUDES} -c -o $@ $<

clean:
	-rm -f $(TGT) $(OBJ) *~ *.o
